# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bb927ea79ba0a5d68e354ddc3babc6101d8e1a85630a85ee2857674905976eb141563325c96b7770db24fef54f582ba006e6fd50a77945598326f1437a7640e

test:
  secret_key_base: 6fdb7a5789e49d98f997b4b3e83304cd7311b2a13e94b03622596b318685da09934e464cfa79ee8afc7b6388bf4b5bfb3839c44f9ce9072999cc3aa171d2110b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
